%% Actual STUDY Creation
% This section contains the code to create the STUDY structure automatically
% based on the directory structure and file naming conventions determined
% in the epoching_Study_faux_pas.m.

% Paste the commands copied from the command prompt after the line
% containing the three dots (...). Uncomment the code and run this part to create the STUDY.
% WARNING! You must change the name of the study

selpath = uigetdir('Choose parent folder containing participants data');
% Change the current working directory to the selected path
cd(selpath);

[STUDY ALLEEG] = std_editset( STUDY, [], 'name','faux_pass_CongIncongNeutral', ...
'task','ERN','commands',{ ...
{'index',1,'load',[selpath filesep 'P1' filesep 'Cong_epochs.set'],'subject','1','condition','Cong'}, ...
{'index',2,'load',[selpath filesep 'P1' filesep 'Incong_epochs.set'],'subject','1','condition','Incong'}, ...
{'index',3,'load',[selpath filesep 'P1' filesep 'Neutral_epochs.set'],'subject','1','condition','Neutral'}, ...
{'index',4,'load',[selpath filesep 'P10' filesep 'Cong_epochs.set'],'subject','2','condition','Cong'}, ...
{'index',5,'load',[selpath filesep 'P10' filesep 'Incong_epochs.set'],'subject','2','condition','Incong'}, ...
{'index',6,'load',[selpath filesep 'P10' filesep 'Neutral_epochs.set'],'subject','2','condition','Neutral'}, ...
{'index',7,'load',[selpath filesep 'P11' filesep 'Cong_epochs.set'],'subject','3','condition','Cong'}, ...
{'index',8,'load',[selpath filesep 'P11' filesep 'Incong_epochs.set'],'subject','3','condition','Incong'}, ...
{'index',9,'load',[selpath filesep 'P11' filesep 'Neutral_epochs.set'],'subject','3','condition','Neutral'}, ...
{'index',10,'load',[selpath filesep 'P12' filesep 'Cong_epochs.set'],'subject','4','condition','Cong'}, ...
{'index',11,'load',[selpath filesep 'P12' filesep 'Incong_epochs.set'],'subject','4','condition','Incong'}, ...
{'index',12,'load',[selpath filesep 'P12' filesep 'Neutral_epochs.set'],'subject','4','condition','Neutral'}, ...
{'index',13,'load',[selpath filesep 'P14' filesep 'Cong_epochs.set'],'subject','5','condition','Cong'}, ...
{'index',14,'load',[selpath filesep 'P14' filesep 'Incong_epochs.set'],'subject','5','condition','Incong'}, ...
{'index',15,'load',[selpath filesep 'P14' filesep 'Neutral_epochs.set'],'subject','5','condition','Neutral'}, ...
{'index',16,'load',[selpath filesep 'P15' filesep 'Cong_epochs.set'],'subject','6','condition','Cong'}, ...
{'index',17,'load',[selpath filesep 'P15' filesep 'Incong_epochs.set'],'subject','6','condition','Incong'}, ...
{'index',18,'load',[selpath filesep 'P15' filesep 'Neutral_epochs.set'],'subject','6','condition','Neutral'}, ...
{'index',19,'load',[selpath filesep 'P17' filesep 'Cong_epochs.set'],'subject','7','condition','Cong'}, ...
{'index',20,'load',[selpath filesep 'P17' filesep 'Incong_epochs.set'],'subject','7','condition','Incong'}, ...
{'index',21,'load',[selpath filesep 'P17' filesep 'Neutral_epochs.set'],'subject','7','condition','Neutral'}, ...
{'index',22,'load',[selpath filesep 'P2' filesep 'Cong_epochs.set'],'subject','8','condition','Cong'}, ...
{'index',23,'load',[selpath filesep 'P2' filesep 'Incong_epochs.set'],'subject','8','condition','Incong'}, ...
{'index',24,'load',[selpath filesep 'P2' filesep 'Neutral_epochs.set'],'subject','8','condition','Neutral'}, ...
{'index',25,'load',[selpath filesep 'P21' filesep 'Cong_epochs.set'],'subject','9','condition','Cong'}, ...
{'index',26,'load',[selpath filesep 'P21' filesep 'Incong_epochs.set'],'subject','9','condition','Incong'}, ...
{'index',27,'load',[selpath filesep 'P21' filesep 'Neutral_epochs.set'],'subject','9','condition','Neutral'}, ...
{'index',28,'load',[selpath filesep 'P22' filesep 'Cong_epochs.set'],'subject','10','condition','Cong'}, ...
{'index',29,'load',[selpath filesep 'P22' filesep 'Incong_epochs.set'],'subject','10','condition','Incong'}, ...
{'index',30,'load',[selpath filesep 'P22' filesep 'Neutral_epochs.set'],'subject','10','condition','Neutral'}, ...
{'index',31,'load',[selpath filesep 'P23' filesep 'Cong_epochs.set'],'subject','11','condition','Cong'}, ...
{'index',32,'load',[selpath filesep 'P23' filesep 'Incong_epochs.set'],'subject','11','condition','Incong'}, ...
{'index',33,'load',[selpath filesep 'P23' filesep 'Neutral_epochs.set'],'subject','11','condition','Neutral'}, ...
{'index',34,'load',[selpath filesep 'P24' filesep 'Cong_epochs.set'],'subject','12','condition','Cong'}, ...
{'index',35,'load',[selpath filesep 'P24' filesep 'Incong_epochs.set'],'subject','12','condition','Incong'}, ...
{'index',36,'load',[selpath filesep 'P24' filesep 'Neutral_epochs.set'],'subject','12','condition','Neutral'}, ...
{'index',37,'load',[selpath filesep 'P25' filesep 'Cong_epochs.set'],'subject','13','condition','Cong'}, ...
{'index',38,'load',[selpath filesep 'P25' filesep 'Incong_epochs.set'],'subject','13','condition','Incong'}, ...
{'index',39,'load',[selpath filesep 'P25' filesep 'Neutral_epochs.set'],'subject','13','condition','Neutral'}, ...
{'index',40,'load',[selpath filesep 'P26' filesep 'Cong_epochs.set'],'subject','14','condition','Cong'}, ...
{'index',41,'load',[selpath filesep 'P26' filesep 'Incong_epochs.set'],'subject','14','condition','Incong'}, ...
{'index',42,'load',[selpath filesep 'P26' filesep 'Neutral_epochs.set'],'subject','14','condition','Neutral'}, ...
{'index',43,'load',[selpath filesep 'P27' filesep 'Cong_epochs.set'],'subject','15','condition','Cong'}, ...
{'index',44,'load',[selpath filesep 'P27' filesep 'Incong_epochs.set'],'subject','15','condition','Incong'}, ...
{'index',45,'load',[selpath filesep 'P27' filesep 'Neutral_epochs.set'],'subject','15','condition','Neutral'}, ...
{'index',46,'load',[selpath filesep 'P28' filesep 'Cong_epochs.set'],'subject','16','condition','Cong'}, ...
{'index',47,'load',[selpath filesep 'P28' filesep 'Incong_epochs.set'],'subject','16','condition','Incong'}, ...
{'index',48,'load',[selpath filesep 'P28' filesep 'Neutral_epochs.set'],'subject','16','condition','Neutral'}, ...
{'index',49,'load',[selpath filesep 'P29' filesep 'Cong_epochs.set'],'subject','17','condition','Cong'}, ...
{'index',50,'load',[selpath filesep 'P29' filesep 'Incong_epochs.set'],'subject','17','condition','Incong'}, ...
{'index',51,'load',[selpath filesep 'P29' filesep 'Neutral_epochs.set'],'subject','17','condition','Neutral'}, ...
{'index',52,'load',[selpath filesep 'P3' filesep 'Cong_epochs.set'],'subject','18','condition','Cong'}, ...
{'index',53,'load',[selpath filesep 'P3' filesep 'Incong_epochs.set'],'subject','18','condition','Incong'}, ...
{'index',54,'load',[selpath filesep 'P3' filesep 'Neutral_epochs.set'],'subject','18','condition','Neutral'}, ...
{'index',55,'load',[selpath filesep 'P30' filesep 'Cong_epochs.set'],'subject','19','condition','Cong'}, ...
{'index',56,'load',[selpath filesep 'P30' filesep 'Incong_epochs.set'],'subject','19','condition','Incong'}, ...
{'index',57,'load',[selpath filesep 'P30' filesep 'Neutral_epochs.set'],'subject','19','condition','Neutral'}, ...
{'index',58,'load',[selpath filesep 'P31' filesep 'Cong_epochs.set'],'subject','20','condition','Cong'}, ...
{'index',59,'load',[selpath filesep 'P31' filesep 'Incong_epochs.set'],'subject','20','condition','Incong'}, ...
{'index',60,'load',[selpath filesep 'P31' filesep 'Neutral_epochs.set'],'subject','20','condition','Neutral'}, ...
{'index',61,'load',[selpath filesep 'P32' filesep 'Cong_epochs.set'],'subject','21','condition','Cong'}, ...
{'index',62,'load',[selpath filesep 'P32' filesep 'Incong_epochs.set'],'subject','21','condition','Incong'}, ...
{'index',63,'load',[selpath filesep 'P32' filesep 'Neutral_epochs.set'],'subject','21','condition','Neutral'}, ...
{'index',64,'load',[selpath filesep 'P33' filesep 'Cong_epochs.set'],'subject','22','condition','Cong'}, ...
{'index',65,'load',[selpath filesep 'P33' filesep 'Incong_epochs.set'],'subject','22','condition','Incong'}, ...
{'index',66,'load',[selpath filesep 'P33' filesep 'Neutral_epochs.set'],'subject','22','condition','Neutral'}, ...
{'index',67,'load',[selpath filesep 'P34' filesep 'Cong_epochs.set'],'subject','23','condition','Cong'}, ...
{'index',68,'load',[selpath filesep 'P34' filesep 'Incong_epochs.set'],'subject','23','condition','Incong'}, ...
{'index',69,'load',[selpath filesep 'P34' filesep 'Neutral_epochs.set'],'subject','23','condition','Neutral'}, ...
{'index',70,'load',[selpath filesep 'P35' filesep 'Cong_epochs.set'],'subject','24','condition','Cong'}, ...
{'index',71,'load',[selpath filesep 'P35' filesep 'Incong_epochs.set'],'subject','24','condition','Incong'}, ...
{'index',72,'load',[selpath filesep 'P35' filesep 'Neutral_epochs.set'],'subject','24','condition','Neutral'}, ...
{'index',73,'load',[selpath filesep 'P36' filesep 'Cong_epochs.set'],'subject','25','condition','Cong'}, ...
{'index',74,'load',[selpath filesep 'P36' filesep 'Incong_epochs.set'],'subject','25','condition','Incong'}, ...
{'index',75,'load',[selpath filesep 'P36' filesep 'Neutral_epochs.set'],'subject','25','condition','Neutral'}, ...
{'index',76,'load',[selpath filesep 'P37' filesep 'Cong_epochs.set'],'subject','26','condition','Cong'}, ...
{'index',77,'load',[selpath filesep 'P37' filesep 'Incong_epochs.set'],'subject','26','condition','Incong'}, ...
{'index',78,'load',[selpath filesep 'P37' filesep 'Neutral_epochs.set'],'subject','26','condition','Neutral'}, ...
{'index',79,'load',[selpath filesep 'P4' filesep 'Cong_epochs.set'],'subject','27','condition','Cong'}, ...
{'index',80,'load',[selpath filesep 'P4' filesep 'Incong_epochs.set'],'subject','27','condition','Incong'}, ...
{'index',81,'load',[selpath filesep 'P4' filesep 'Neutral_epochs.set'],'subject','27','condition','Neutral'}, ...
{'index',82,'load',[selpath filesep 'P5' filesep 'Cong_epochs.set'],'subject','28','condition','Cong'}, ...
{'index',83,'load',[selpath filesep 'P5' filesep 'Incong_epochs.set'],'subject','28','condition','Incong'}, ...
{'index',84,'load',[selpath filesep 'P5' filesep 'Neutral_epochs.set'],'subject','28','condition','Neutral'}, ...
{'index',85,'load',[selpath filesep 'P6' filesep 'Cong_epochs.set'],'subject','29','condition','Cong'}, ...
{'index',86,'load',[selpath filesep 'P6' filesep 'Incong_epochs.set'],'subject','29','condition','Incong'}, ...
{'index',87,'load',[selpath filesep 'P6' filesep 'Neutral_epochs.set'],'subject','29','condition','Neutral'}, ...
{'index',88,'load',[selpath filesep 'P7' filesep 'Cong_epochs.set'],'subject','30','condition','Cong'}, ...
{'index',89,'load',[selpath filesep 'P7' filesep 'Incong_epochs.set'],'subject','30','condition','Incong'}, ...
{'index',90,'load',[selpath filesep 'P7' filesep 'Neutral_epochs.set'],'subject','30','condition','Neutral'}, ...
{'index',91,'load',[selpath filesep 'P8' filesep 'Cong_epochs.set'],'subject','31','condition','Cong'}, ...
{'index',92,'load',[selpath filesep 'P8' filesep 'Incong_epochs.set'],'subject','31','condition','Incong'}, ...
{'index',93,'load',[selpath filesep 'P8' filesep 'Neutral_epochs.set'],'subject','31','condition','Neutral'}, ...
{'index',94,'load',[selpath filesep 'P9' filesep 'Cong_epochs.set'],'subject','32','condition','Cong'}, ...
{'index',95,'load',[selpath filesep 'P9' filesep 'Incong_epochs.set'],'subject','32','condition','Incong'}, ...
{'index',96,'load',[selpath filesep 'P9' filesep 'Neutral_epochs.set'],'subject','32','condition','Neutral'} ...
 },'updatedat','on','rmclust','on' );
% %
% % The code above generates the STUDY structure by automatically loading EEG
% % datasets for each participant and condition. The file paths are
% % constructed based on the selected parent folder (selpath) and the naming
% % conventions for subjects (P1, P2, etc.) and conditions (Cog, Incog,
% % Neutral). The resulting STUDY structure organizes the datasets for
% % subsequent analysis.
% 
% % WARNING! You must change the name of the study
% %
% CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
% [STUDY EEG] = pop_savestudy( STUDY, EEG, 'filename','faux_passCongIncongNeutral.study','filepath',[selpath filesep 'code']);
% %

